### ISSUE TITLE
Repository has no software license

### ISSUE THREAD

**Issue by mchlumsky** [mrlesmithjr/python-powerdns-management#2]
This repository has no license. I would love to you use the script!

Can you please add a license?

https://help.github.com/articles/licensing-a-repository/

**Comment by mrlesmithjr** [comment]
Done. Thanks for pointing that out.

**Comment by mrlesmithjr** [comment]
@mchlumsky We good to close this issue?

**Comment by mchlumsky** [comment]
Yes. Thank you!

**Comment by mrlesmithjr** [comment]
Perfect, just trying to clean up some of these repos.
